name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        cd ./app-react
        npm install
        
    - name: Run tests
      run: |
        cd ./app-react
        npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        cd ./app-react
        npm install

    - name: Build application
      run: |
        cd ./app-react
        npm run build

    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.FRONTEND_SSH_HOST }}
        EC2_USER: ${{ secrets.FRONTEND_USER_NAME }}
        APP_DIR: /home/ubuntu/parcial-frontend/app-react
      run: |
        echo "$EC2_PRIVATE_KEY" | tr -d '\r' > ec2_key
        chmod 600 ec2_key
        ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
        
          sudo apt install apache2
          npm install

          cd parcial-frontend &&
          cd app-react && 

          git fetch --all &&
          git reset --hard origin/main &&
          git pull origin main &&
          
          npm run build 
          sudo cp -r build/* /var/www/html/ &&
          sudo systemctl restart apache2
        '
